version: "3.9"

services:
  frontend:
    image: todo-frontend
    container_name: todo-frontend
    build:
      context: ./front
      dockerfile: Dockerfile
      target: runner
      args:
        VITE_API_URL: http://localhost:3000
    ports:
      - "80:80"
    # env_file:
    #   - ./front/.env.docker

  backend:
    image: todo-backend
    container_name: todo-backend
    build:
      context: ./back
      dockerfile: Dockerfile
      target: runner
    ports:
      - "3000:3000"
    env_file:
      - ./back/.env.backend
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: todo-mongoDB
    volumes:
      - todo-db:/data/db
    env_file:
      - ./back/.env.mongoDB

  mongo-express:
    image: mongo-express:latest
    container_name: todo-mongoExpress
    ports:
      - "8081:8081"
    env_file:
      - ./back/.env.mongoExpress
    depends_on:
      - mongodb

volumes:
  todo-db: